### ISSUE TITLE
`difference` doesn't match the behavior of the standard sets

### ISSUE THREAD

**Issue by cuviper** [udoprog/bittle#3]
As documented, `BitsOwned::difference` "returns the elements in the second set which are not part of the first." Similarly, `BitsMut::difference_assign` "assigns the elements in the second set which are not part of the first."

However, this is the opposite of both [`BTreeSet::difference`](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.difference) and [`HashSet::difference`](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.difference), which return iterators of items that are "in `self` but not in `other`". Is that intentional?

---

My motivation: I was going to suggest and contribute `Sub` and `SubAssign for Set<T>`, which I thought would be simple to base on `difference`, but their result was not what I expected.

```rust
owned_ops!(Sub::sub, Set<T>, difference);
assign_ops!(SubAssign::sub_assign, Set<T>, difference_assign);
```

**Comment by udoprog** [comment]
Please do change it! I don't remember from where it stemmed, but it's clearly not the most typical. Or just an oversight ;).

I'll happily bake a breaking release once it's fixed.

**Comment by cuviper** [comment]
Great, thanks for the quick response!
